//! Ported from `src/grace/harness/tape.py`'s `Tape` dataclass and
//! `_read_jsonl` loader, plus the event-stream diff. This is a faithful,
//! read-only port of the tape *format*: it reads exactly what `corpus/`
//! already contains (`meta.json`, `events.jsonl`, `llm.jsonl`, `stt.jsonl`,
//! `snapshots.jsonl`, `dispatch.jsonl`, `audio.jsonl`), so nothing here can
//! accidentally write to or regenerate a tape - that stays a
//! human-reviewed, Python-only operation per PLAN.md §13.

use anyhow::{Context, Result};
use serde_json::Value;
use std::path::Path;

/// One recorded (or generated) session, exactly as `src/grace/harness/tape.py::Tape` models it.
#[derive(Debug, Clone, Default)]
pub struct Tape {
    pub dir: String,
    pub meta: Value,
    pub events: Vec<Value>,
    pub llm: Vec<Value>,
    pub stt: Vec<Value>,
    pub snapshots: Vec<Value>,
    pub dispatch: Vec<Value>,
    pub audio: Vec<Value>,
}

fn read_jsonl(path: &Path) -> Result<Vec<Value>> {
    if !path.exists() {
        return Ok(Vec::new());
    }
    let text = std::fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))?;
    let mut out = Vec::new();
    for (lineno, line) in text.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let value: Value = serde_json::from_str(line)
            .with_context(|| format!("{}:{}: invalid JSON line", path.display(), lineno + 1))?;
        out.push(value);
    }
    Ok(out)
}

impl Tape {
    /// Loads a tape from a session directory (`recordings/<ts>/` or one
    /// `corpus/<scenario>/` entry).
    pub fn load(dir: &Path) -> Result<Self> {
        let meta_path = dir.join("meta.json");
        let meta: Value = if meta_path.exists() {
            let text = std::fs::read_to_string(&meta_path)
                .with_context(|| format!("reading {}", meta_path.display()))?;
            serde_json::from_str(&text).with_context(|| format!("parsing {}", meta_path.display()))?
        } else {
            Value::Null
        };

        Ok(Self {
            dir: dir.display().to_string(),
            meta,
            events: read_jsonl(&dir.join("events.jsonl"))?,
            llm: read_jsonl(&dir.join("llm.jsonl"))?,
            stt: read_jsonl(&dir.join("stt.jsonl"))?,
            snapshots: read_jsonl(&dir.join("snapshots.jsonl"))?,
            dispatch: read_jsonl(&dir.join("dispatch.jsonl"))?,
            audio: read_jsonl(&dir.join("audio.jsonl"))?,
        })
    }

    /// `true` when `meta.json` marks this tape as generated by
    /// `harness/generate.py` rather than recorded from a live session.
    pub fn is_synthetic(&self) -> bool {
        self.meta
            .get("synthetic")
            .and_then(Value::as_bool)
            .unwrap_or(false)
    }

    /// The bare `GraceEvent` payloads, in order, with the tape's `i`/`t_ms`
    /// framing stripped - what `diff_event_streams` compares.
    pub fn event_payloads(&self) -> Vec<Value> {
        self.events
            .iter()
            .filter_map(|entry| entry.get("event").cloned())
            .collect()
    }

    /// Loads every scenario directory directly under `corpus_dir` (each one
    /// a `Tape`), sorted by directory name for a stable report order.
    pub fn load_corpus(corpus_dir: &Path) -> Result<Vec<Tape>> {
        let mut dirs: Vec<_> = std::fs::read_dir(corpus_dir)
            .with_context(|| format!("reading corpus dir {}", corpus_dir.display()))?
            .filter_map(|e| e.ok())
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        dirs.sort();
        dirs.into_iter().map(|d| Tape::load(&d)).collect()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Write;

    fn write_tape(dir: &Path, meta: &str, events: &[&str]) {
        std::fs::create_dir_all(dir).unwrap();
        std::fs::write(dir.join("meta.json"), meta).unwrap();
        let mut f = std::fs::File::create(dir.join("events.jsonl")).unwrap();
        for line in events {
            writeln!(f, "{line}").unwrap();
        }
    }

    #[test]
    fn loads_meta_and_events_and_strips_tape_framing() {
        let tmp = std::env::temp_dir().join(format!("grace-harness-test-{}", std::process::id()));
        write_tape(
            &tmp,
            r#"{"session_id": "x", "synthetic": true}"#,
            &[
                r#"{"i": 0, "t_ms": 1.0, "event": {"type": "Idle"}}"#,
                r#"{"i": 1, "t_ms": 2.0, "event": {"type": "WakeWordDetected"}}"#,
            ],
        );

        let tape = Tape::load(&tmp).unwrap();
        assert!(tape.is_synthetic());
        assert_eq!(tape.events.len(), 2);
        assert_eq!(
            tape.event_payloads(),
            vec![
                serde_json::json!({"type": "Idle"}),
                serde_json::json!({"type": "WakeWordDetected"})
            ]
        );

        std::fs::remove_dir_all(&tmp).ok();
    }

    #[test]
    fn missing_optional_streams_read_as_empty_not_an_error() {
        let tmp = std::env::temp_dir().join(format!("grace-harness-test-empty-{}", std::process::id()));
        write_tape(&tmp, "{}", &[]);
        let tape = Tape::load(&tmp).unwrap();
        assert!(tape.llm.is_empty());
        assert!(tape.dispatch.is_empty());
        std::fs::remove_dir_all(&tmp).ok();
    }
}
